## Structure of the book {-}

Chapter \@ref(intro) gives a brief background on the software used in the past in Biological Dosimetry and outlines the reasons to use R and R Shiny as the basis of Biodose Tools.  

Chapter \@ref(manual-get) introduces the user to Biodose Tools and how to use it either online or locally in RStudio. Chapter \@ref(manual-use) introduces the basic design principles behind the user interface, and the usage of the different modules. These two chapters should be sufficient to get most readers comfortable with Biodose Tools itself.

Chapter \@ref(stats-intro) is a comprehensive review of the different statistical methods and tests used and available throughout Biodose Tools, geared towards mathematicians and biologists alike. In particular, \@ref(stats-dicent) discusses the methods used for dicentrics analysis; \@ref(stats-trans), the methods used for translocations; and \@ref(stats-micro), the methods used for micronuclei.

Appendix \@ref(appendix-feedback) explains how to give feedback of the app. In Appendix \@ref(appendix-implementation), a brief technical review of the implementation of Biodose Tools is discussed. In Appendix \@ref(appendix-cite) we provide a small guide to cite Biodose Tools.

To sum it up, this book is a comprehensive reference of Biodose Tools. You can follow the 80/20 rule when reading it. Some sections are there for the sake of completeness, and not all sections are equally useful to the particular use case your laboratory or institution may have to Biodose Tools.

\newpage
