# Introduction {#intro}

## Biological dosimetry {#intro-biodosimetry}

Biological dosimetry aims at estimating the absorbed dose in an individual in which an exposure to ionising radiation (IR) is suspected, by means of analysing biomarkers with a clear dose-effect relationship [@IAEA2011]. A great majority of biomarkers of dose exposure come from the analysis of the induced DNA damage, most of them analysed using cytogenetic techniques such as dicentric, translocation, or micronucleus assays. Dose assessment is based on converting an observed yield of aberrations (e.g., the frequency of dicentrics present in peripheral blood lymphocytes) into an absorbed dose using a pre-established calibration curve. This process requires mathematical models and the assumptions on statistical probability distribution of the aberration in question. First, to establish a calibration curve, blood samples must be uniformly irradiated at several doses and the observed distribution of aberrations is mostly assumed to follow a Poisson distribution. More precisely, it is assumed that for low-LET (linear energy transfer) radiation types, uniform exposures result in dicentric counts that follow a Poisson distribution [@Bauchinger1973; @Edwards1979]. High-LET radiation types tend to show overdispersion [@Virsik1981; @Brame2002; @Puig2011]. Overdispersion also often arises in micronuclei counts and $\gamma$-H2AX foci data [@Vral2011; @Einbeck2018]. Then the observed yields at different doses are used to construct a calibration curve assuming a Linear-Quadratic (LQ) or Linear (L) model, depending on the radiation quality. While low-LET exposures show a linear-quadratic dose-effect relationship, high-LET exposures tend to be linear, [@Edwards1980]. The coefficients of these models can be estimated using maximum likelihood or iteratively reweighted least squares approaches [@Merkle1983].

In case of a radiation accident, the observed distribution of aberration counts is tested for deviations from the Poisson distribution to distinguish homogeneous and heterogeneous exposures. The observed count is inverse regressed by the calibration curve and uncertainties are usually calculated considering only the uncertainty relative to the yield observed or considering also uncertainties coming from the calibration curve [@Edwards1978; @Merkle1983; @Savage2000]. Procedures to consider both sources of uncertainties are not simple, as the error is made up of two components: (a) uncertainties from the distribution of observed counts, and (b) uncertainties from the LQ or L models of the calibration curve [@Merkle1983; @Savage2000]. In case of a heterogeneous exposure, additional distributional assumptions have to be made [@Dolphin1969; @Sasaki1968; @Pujol2016]. Bayesian methods have been recently proposed to consider both sources of uncertainty, and for both, whole-body (homogeneous) and partial-body (heterogeneous) dose assessment [@Ainsbury2014; @Morina2015; @Higueras2015].
