## Statistical considerations {#stats-considerations}

There is a strong evidence that the yields of chromosome aberrations (dicentrics, translocations) or micronuclei ($Y$) are related to exposed dose ($D$) by the linear quadratic equation

\begin{equation} 
  Y = C + \alpha D + \beta D^2
  (\#eq:dose-response-lq)
\end{equation}

or, for high LET radiation, the $\alpha$-term becomes large and eventually the $\beta$-term becomes biologically less relevant and also statistically "masked". In this situation, the the dose response is
approximated by the linear equation

\begin{equation} 
  Y = C + \alpha D
  (\#eq:dose-response-l)
\end{equation}


### Dose-effect curve fitting

The objective of dose-effect or curve fitting is to determine those values of the coefficients $C$, $\alpha$ and $\beta$ which best fit the data points. For dicentrics (see Chapter \@ref(stats-dicent)), irradiation with X or gamma rays produces a distribution of damage which is very well represented by the Poisson distribution [@Edwards1979]. In contrast, neutrons and other types of high LET radiation produce distributions which display overdispersion, where the variance ($\sigma^{2}$) exceeds the mean ($\bar{y}$). Whether the ratio of variance to mean ($\sigma^{2}/\bar{y}$) is a function of dose is at present an open question. For micronuclei (see Chapter \@ref(stats-micro)) the data tend to overdispersion at all doses even with photon irradiation.


### Poisson distribution

The Poisson distribution is named after Simmeon Poisson, a leading French mathematician during the early 1800s. The distribution applies when the random variable is discrete and represents the number of events that occur in a unit-of-scale, such as unit-or-time or unit-of-area. The rate of events occurring is constant and the number of events $k$ are the integers of zero and larger. 

Statistically, a discrete random variable $Y$ is said to have a Poisson distribution with parameter $\lambda > 0$, if, for $k = 0, 1, 2, \dots$ the probability mass function of $Y$ is given by:

\begin{equation}
	f(k; \lambda) = \Pr(Y = k)= \frac{\lambda^k e^{-\lambda}}{k!},
	(\#eq:poisson-dist)
\end{equation}

where

- $e$ is Euler's number ($e$ = 2.71828...),
- $k$! is the factorial of $k$.

The positive real number $\lambda$ is equal to the expected value of $Y$ and also to its variance:
\begin{equation}
	\bar{y} = \operatorname{E}(Y) = \lambda, \quad \sigma^{2} = \operatorname{Var}(Y) = \lambda.
	(\#eq:variance-poisson)
\end{equation}

However, for real count data, it is recommended to calculate the variance defined as
\begin{equation}
\begin{aligned}
  \sigma^{2} = \operatorname{Var}(Y)
  %= \frac{1}{n} \sum_{i=1}^n (y_{i} - \bar{y})^2 
  &= \frac{1}{N - 1} \left[ \sum_{k=1}^{N} k^{2} C_{k} - N \bar{y}^{2} \right] \\
  &= \frac{1}{N - 1} \left[  \sum_{k=1}^{N} k^{2} C_{k} - \frac{1}{N} \left( \sum_{k=1}^{N} k C_{k} \right)^{2} \right]
  ,
\end{aligned}
  (\#eq:variance)
\end{equation}
where

- $N$ is the total number of events,
- $C_{k} = N \cdot \Pr(Y = k)$ is the occurrence count or frequency for event $k$.


### Testing for Poisson

Since most curve fitting methods are based on Poisson statistics, the dicentric cell distribution should be tested for compliance with the Poisson distribution for each dose used to construct the calibration curve. Nowadays, the most widely used test is the $u$-test [@Rao1956; @Savage1970]. The $u$-test statistic is a normalized unit of the dispersion index ($\sigma^{2}/\bar{y}$), which for a Poisson distribution should be unity. $u$-values higher than 1.96 indicate overdispersion (with a two-sided significance level, $\alpha$ = 0.025).

\begin{equation} 
  u = (\sigma^{2}/\bar{y} - 1) \sqrt{\frac{N - 1}{2 (1 - 1/X)}}
  (\#eq:u-value)
\end{equation}

where

- $\sigma^{2}/\bar{y}$ is the dispersion index,
- $u$ is the $u$-value, which for a Poisson distribution should be unity,
- $N$ indicates the number of cells analysed,
- $X = \sum_{k=1}^{N} k C_{k}$ the number of dicentrics (or dicentrics plus rings) detected,
- $C_{k}$ is the count of cells where $k$ dicentrics were detected.

$u$-values of < -1.96 indicate underdispersion. Biologically, underdispersion is very unlikely to occur so values of $u$ lower than -1.96 may be indicative of a problem in data sampling.


### Dose-effect calibration

Adequate curve fitting requires a sufficient number of degrees of freedom to minimize the error on the curve. Ideally, 10 or more doses should be used in the range 0.25–5.0 Gy. For low LET radiation it is not necessary to have data higher than approximately 5.0 Gy and, indeed, beyond this dose there is evidence of saturation of the aberration yield which will lead to a distortion of the $\beta$ coefficient [@Lloyd1983]. For high LET radiation a maximum of 2.0 Gy is suggested.

As most radiation accidents involve doses of less than 1.0 Gy, the lower end of the curve is of particular importance in estimating doses. A significant effort should therefore be made to reduce the statistical uncertainty associated with the $\alpha$ coefficient of yield. It is suggested that several of the calibration doses, certainly a minimum of four, should be in the range of 0.25–1.0 Gy. If the laboratory is capable of obtaining data at doses below 0.25 Gy, this is very desirable. At higher doses, scoring should aim to detect 100 dicentrics at each dose. However at lower doses this is difficult to achieve and instead several thousand cells per point should be scored; a number between 3000 and 5000 is suggested. In all cases, the actual number of cells scored should be dependent on the number of dose points in the low dose region, with the focus on minimizing the error on the fitted curve. 


### Background level

Opinions vary on how to treat the background level of aberrations in fitting dose response data. In general there are three approaches: (a) a dose point at zero Gy is included in the curve fitting procedure, (b) the zero dose point is ignored, or else (c) the zero dose point is represented in every fitting procedure by a standard background value. 

If the measured yield at zero dose is used as one of the data points for the curve fitting (as used in the curve fitting presented above), the background becomes a variable parameter. However, since the yield in unirradiated cells is usually low, often none are observed so the measured yield at zero dose is zero. As discussed, at low doses, the statistical resolution of the data points is generally low. Thus, including the zero dose point in the curve fitting procedure can sometimes lead to negative estimates of the background value ($C$) and negative linear coefficients ($\alpha$), which obviously have no biological basis. Some investigators resolve this problem by ignoring zero dose data points and constraining the curve to pass through the origin (to be implemented in Biodose Tools in the future). There are, however, sufficient data published from surveys of subjects exposed only to background radiation to show that there is a small positive background level of aberrations. An alternative method adopted by some workers is therefore to use a small positive background value as a data point and to ascribe a large percentage of uncertainty to it. Ideally a laboratory should generate its own background data, although this requires the analysis of many thousands of cells. A consensus has emerged that the background level of dicentrics is ~0.5–1.0 per 1000 cells [@Lloyd1980] whilst for translocations [@Sigurdson2008] and micronuclei [@Fenech1993] the control values are higher.
